services:
  postgres:
    image: postgres:15
    container_name: notes-postgres
    environment:
      POSTGRES_DB: notes_app
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  pgweb:
    image: sosedoff/pgweb
    container_name: notes-pgweb
    ports:
      - "8080:8081"
    environment:
      PGWEB_DATABASE_URL: postgres://postgres:password@postgres:5432/notes_app?sslmode=disable
    depends_on:
      postgres:
        condition: service_healthy

  backend:
    build: .
    container_name: notes-backend
    ports:
      - "4000:4000"
    environment:
      - NODE_ENV=development
      - PORT=4000
      - JWT_SECRET=your-super-secret-jwt-key-here
      - JWT_EXPIRES_IN=7d
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_NAME=notes_app
      - DB_USER=postgres
      - DB_PASSWORD=password
    depends_on:
      postgres:
        condition: service_healthy
    volumes:
      - .:/app
      - /app/node_modules
    command: sh -c "npm run migrate && npm run dev"

volumes:
  postgres_data: